apiVersion: v1
kind: Pod
metadata:
  name: dna-model-validation
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/jeg076/dna-interaction:latest
    command: ["python", "train.py"]
    volumeMounts:
    - mountPath: /workspace/data
      name: jeg076-pvc
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 8G
        cpu: 4
  restartPolicy: Never
  volumes:
    - name: jeg076-pvc
      persistentVolumeClaim:
        claimName: jeg076-pvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/cuda.runtime.major
            operator: In
            values:
            - "12"
          - key: nvidia.com/cuda.runtime.minor
            operator: In
            values:
            - "2"